// Masai Mara wildlife checklist data.
// category: predator | herbivore | primate | reptile | bird
// rarity: common | uncommon | rare  (rough guide, not scientific)

const SPECIES = [
  // ---- Big cats & predators ----
  { id: 'lion', name: 'Lion', sciName: 'Panthera leo', category: 'predator', rarity: 'common', big5: true,
    habitat: 'Open savanna, often resting in shade near the Mara River',
    fact: 'A pride\'s roar can be heard up to 8km away, and the Mara\'s prides are some of the largest in Africa, sometimes over 20 lions.',
    icon: { shape: 'quadruped', size: 'xl', color: '#c9963c', mane: true, maneColor: '#7a4a1e', tailTuft: true, bg1: '#f6e6bd', bg2: '#d8a94c' } },
  { id: 'leopard', name: 'Leopard', sciName: 'Panthera pardus', category: 'predator', rarity: 'uncommon', big5: true,
    habitat: 'Riverine forest and thick bush, often draped over tree branches',
    fact: 'Leopards can drag a kill twice their own body weight up into a tree to keep it safe from lions and hyenas.',
    icon: { shape: 'quadruped', size: 'l', color: '#d9a24a', pattern: 'spots', tailTuft: false, bg1: '#f2e2b8', bg2: '#c98f3a' } },
  { id: 'cheetah', name: 'Cheetah', sciName: 'Acinonyx jubatus', category: 'predator', rarity: 'uncommon',
    habitat: 'Open plains where it can use its speed',
    fact: 'The cheetah can accelerate from 0 to 100km/h in about three seconds - faster than most sports cars.',
    icon: { shape: 'quadruped', size: 'l', color: '#e0b262', pattern: 'spots', longNeck: true, bg1: '#f4e8c8', bg2: '#d8b25f' } },
  { id: 'spotted-hyena', name: 'Spotted Hyena', sciName: 'Crocuta crocuta', category: 'predator', rarity: 'common',
    habitat: 'Clans denning in old aardvark burrows across the plains',
    fact: 'Spotted hyenas are highly skilled hunters, not just scavengers - they make up to 95% of their own kills.',
    icon: { shape: 'quadruped', size: 'm', color: '#b8a184', pattern: 'patches', bg1: '#e8ddc8', bg2: '#a89577' } },
  { id: 'black-backed-jackal', name: 'Black-backed Jackal', sciName: 'Lupulella mesomelas', category: 'predator', rarity: 'common',
    habitat: 'Plains and woodland edges, often seen trotting alone at dawn',
    fact: 'Jackal pairs mate for life and both parents, plus older offspring, help raise each new litter of pups.',
    icon: { shape: 'quadruped', size: 's', color: '#b5793f', mane: true, maneColor: '#3a3a3a', bg1: '#eadfc4', bg2: '#a8783f' } },
  { id: 'bat-eared-fox', name: 'Bat-eared Fox', sciName: 'Otocyon megalotis', category: 'predator', rarity: 'uncommon',
    habitat: 'Short grass plains, usually in small family groups',
    fact: 'Its huge ears aren\'t just for hearing predators - they radiate heat and can detect the sound of insects moving underground.',
    icon: { shape: 'quadruped', size: 's', color: '#cbb48c', bg1: '#efe6cf', bg2: '#b8a37c' } },
  { id: 'african-wild-dog', name: 'African Wild Dog', sciName: 'Lycaon pictus', category: 'predator', rarity: 'rare',
    habitat: 'Wide-ranging packs, a rare and exciting sighting',
    fact: 'One of Africa\'s most endangered carnivores, wild dog packs hunt cooperatively with an astonishing 80% hunt success rate.',
    icon: { shape: 'quadruped', size: 'm', color: '#c9a878', pattern: 'patches', bg1: '#e8dcc2', bg2: '#b08f5c' } },
  { id: 'serval', name: 'Serval', sciName: 'Leptailurus serval', category: 'predator', rarity: 'rare',
    habitat: 'Tall grassland near water, mostly at dusk',
    fact: 'Relative to body size, the serval has the largest ears of any cat, letting it pinpoint rodents hidden deep in grass.',
    icon: { shape: 'quadruped', size: 's', color: '#e0b95f', pattern: 'spots', longNeck: true, bg1: '#f4ecc9', bg2: '#dcb85f' } },
  { id: 'caracal', name: 'Caracal', sciName: 'Caracal caracal', category: 'predator', rarity: 'rare',
    habitat: 'Rocky outcrops and thick cover, mostly nocturnal',
    fact: 'Caracals can leap over 3 metres straight up to swat birds out of the air.',
    icon: { shape: 'quadruped', size: 's', color: '#c9713f', bg1: '#ecd2b8', bg2: '#b8663a' } },
  { id: 'honey-badger', name: 'Honey Badger', sciName: 'Mellivora capensis', category: 'predator', rarity: 'rare',
    habitat: 'Widespread but rarely seen, often solitary and fearless',
    fact: 'Famous for its fearlessness, the honey badger is one of very few animals known to actively fend off lions.',
    icon: { shape: 'smallMammal', color: '#3a3a3a', twoTone: true, bg1: '#dcdcd4', bg2: '#8a8a82' } },

  // ---- Big herbivores ----
  { id: 'african-elephant', name: 'African Bush Elephant', sciName: 'Loxodonta africana', category: 'herbivore', rarity: 'common', big5: true,
    habitat: 'Woodland and riverbanks, moving in tight-knit family herds',
    fact: 'Elephants communicate over several kilometres using infrasound rumbles too low for humans to hear.',
    icon: { shape: 'elephant', color: '#8f8a80', tusks: true, bg1: '#e4ded2', bg2: '#8f8a80' } },
  { id: 'black-rhino', name: 'Black Rhinoceros', sciName: 'Diceros bicornis', category: 'herbivore', rarity: 'rare', big5: true,
    habitat: 'Dense bush, critically endangered - a special sighting',
    fact: 'Despite the name, black rhinos are grey - the name distinguishes their pointed lip (for browsing) from the white rhino\'s wide, flat lip.',
    icon: { shape: 'rhino', color: '#918070', bg1: '#e2d8c8', bg2: '#8a7a68' } },
  { id: 'cape-buffalo', name: 'African (Cape) Buffalo', sciName: 'Syncerus caffer', category: 'herbivore', rarity: 'common', big5: true,
    habitat: 'Large herds on the plains, never far from water',
    fact: 'Nicknamed "black death" by hunters, buffalo are considered the most dangerous of the Big Five due to unpredictable charges.',
    icon: { shape: 'quadruped', size: 'l', color: '#4a453e', horn: 'ringed', hornColor: '#2a2620', bg1: '#d8d4c8', bg2: '#4a453e' } },
  { id: 'hippopotamus', name: 'Hippopotamus', sciName: 'Hippopotamus amphibius', category: 'herbivore', rarity: 'common',
    habitat: 'Pods wallowing in the Mara River and Talek River',
    fact: 'Hippos secrete a natural reddish oily substance often called "blood sweat" that acts as sunscreen and an antibiotic.',
    icon: { shape: 'hippo', color: '#8a8577', bg1: '#dcd8c8', bg2: '#7a7568' } },
  { id: 'giraffe', name: 'Masai Giraffe', sciName: 'Giraffa tippelskirchi', category: 'herbivore', rarity: 'common',
    habitat: 'Acacia woodland, browsing on treetops',
    fact: 'A giraffe\'s heart weighs around 11kg and generates roughly double the blood pressure of a human to pump blood up that long neck.',
    icon: { shape: 'quadruped', size: 'l', giraffe: true, color: '#d9a94f', pattern: 'patches', bg1: '#f2e4bd', bg2: '#c99b3f' } },
  { id: 'common-zebra', name: 'Plains Zebra', sciName: 'Equus quagga', category: 'herbivore', rarity: 'common',
    habitat: 'Huge herds across the plains, mixing with wildebeest',
    fact: 'Every zebra\'s stripe pattern is as unique as a human fingerprint, helping foals recognise their own mother in a herd.',
    icon: { shape: 'quadruped', size: 'm', color: '#f2efe6', pattern: 'stripes', mane: true, maneColor: '#2b2b2b', bg1: '#f2efe6', bg2: '#3a3a3a' } },
  { id: 'blue-wildebeest', name: 'Blue Wildebeest', sciName: 'Connochaetes taurinus', category: 'herbivore', rarity: 'common',
    habitat: 'The star of the Great Migration, in herds of thousands',
    fact: 'Over 1.5 million wildebeest cross the Mara River each year in one of the largest land mammal migrations on Earth.',
    icon: { shape: 'quadruped', size: 'm', color: '#5a5a52', mane: true, maneColor: '#1e1e1a', horn: 'lyre', hornColor: '#2a2a2a', bg1: '#d8d6ca', bg2: '#4a4a44' } },
  { id: 'impala', name: 'Impala', sciName: 'Aepyceros melampus', category: 'herbivore', rarity: 'common',
    habitat: 'Woodland edges, in large mixed or bachelor herds',
    fact: 'An impala can leap 3 metres high and 10 metres in a single bound to escape predators.',
    icon: { shape: 'quadruped', size: 's', color: '#c9873f', horn: 'lyre', bg1: '#eeddc0', bg2: '#b87d3a' } },
  { id: 'thomsons-gazelle', name: "Thomson's Gazelle", sciName: 'Eudorcas thomsonii', category: 'herbivore', rarity: 'common',
    habitat: 'Short grass plains, constantly flicking its tail',
    fact: '"Tommies" stot - bouncing stiff-legged into the air - to signal to predators that they\'ve been spotted and a chase is pointless.',
    icon: { shape: 'quadruped', size: 's', color: '#d9b978', horn: 'straight', bg1: '#f2e8cc', bg2: '#c9a866' } },
  { id: 'grants-gazelle', name: "Grant's Gazelle", sciName: 'Nanger granti', category: 'herbivore', rarity: 'common',
    habitat: 'Drier open plains, larger than the Thomson\'s gazelle',
    fact: 'Grant\'s gazelles can go for extended periods without drinking water, getting most of their moisture from plants.',
    icon: { shape: 'quadruped', size: 's', color: '#e2cf9e', horn: 'lyre', bg1: '#f4ecd4', bg2: '#d2ba82' } },
  { id: 'topi', name: 'Topi', sciName: 'Damaliscus lunatus jimela', category: 'herbivore', rarity: 'common',
    habitat: 'Grassy plains, often standing sentinel on old termite mounds',
    fact: 'Topi are considered one of the fastest antelope in Africa and often stand atop termite mounds to watch for predators.',
    icon: { shape: 'quadruped', size: 'm', color: '#7a4a3a', pattern: 'patches', horn: 'lyre', bg1: '#dcc4ac', bg2: '#6a3f30' } },
  { id: 'cokes-hartebeest', name: "Coke's Hartebeest", sciName: 'Alcelaphus buselaphus cokii', category: 'herbivore', rarity: 'common',
    habitat: 'Open plains, recognisable by its long face and sloped back',
    fact: 'Locally called "Kongoni", its oddly elongated skull houses large sinuses thought to help with cooling.',
    icon: { shape: 'quadruped', size: 'm', color: '#b98a56', horn: 'lyre', bg1: '#ecd8ba', bg2: '#a97a48' } },
  { id: 'waterbuck', name: 'Waterbuck', sciName: 'Kobus ellipsiprymnus', category: 'herbivore', rarity: 'common',
    habitat: 'Always close to rivers and marshes',
    fact: 'Waterbuck have a natural oily secretion in their coat with a musky odour that some believe deters predators from eating them.',
    icon: { shape: 'quadruped', size: 'm', color: '#786858', horn: 'ringed', bg1: '#dcd4c4', bg2: '#68584a' } },
  { id: 'eland', name: 'Common Eland', sciName: 'Taurotragus oryx', category: 'herbivore', rarity: 'uncommon',
    habitat: 'Open plains and woodland, Africa\'s largest antelope',
    fact: 'Despite weighing up to 900kg, elands are excellent jumpers and can clear fences over 2.5 metres tall.',
    icon: { shape: 'quadruped', size: 'l', color: '#b39a78', horn: 'spiral', bg1: '#e8dcc4', bg2: '#a38a68' } },
  { id: 'kudu', name: 'Greater Kudu', sciName: 'Tragelaphus strepsiceros', category: 'herbivore', rarity: 'rare',
    habitat: 'Thick bush and rocky hillsides',
    fact: 'The male\'s spectacular spiralling horns can grow to over 1.2 metres and make one and a half graceful turns.',
    icon: { shape: 'quadruped', size: 'm', color: '#8a8272', pattern: 'stripes', horn: 'spiral', bg1: '#d8d4c4', bg2: '#7a7262' } },
  { id: 'dik-dik', name: "Kirk's Dik-dik", sciName: 'Madoqua kirkii', category: 'herbivore', rarity: 'uncommon',
    habitat: 'Dense thicket, seen darting in monogamous pairs',
    fact: 'One of the smallest antelope in the world, standing just 40cm tall, and it mates for life.',
    icon: { shape: 'quadruped', size: 's', color: '#c9a878', horn: 'short', bg1: '#eeddc0', bg2: '#b8935f' } },
  { id: 'warthog', name: 'Common Warthog', sciName: 'Phacochoerus africanus', category: 'herbivore', rarity: 'common',
    habitat: 'Open grassland, trotting with tail held straight up',
    fact: 'Warthogs run backwards into burrows so they can face outward and defend themselves with their tusks.',
    icon: { shape: 'quadruped', size: 'm', color: '#5a534a', tusks: true, mane: true, maneColor: '#2a271f', tailTuft: true, bg1: '#d8d2c4', bg2: '#4a453e' } },
  { id: 'olive-baboon', name: 'Olive Baboon', sciName: 'Papio anubis', category: 'primate', rarity: 'common',
    habitat: 'Troops of dozens, active on the ground and in trees',
    fact: 'Baboon troops have a strict social hierarchy, and lower-ranking members often groom higher-ranking ones to build alliances.',
    icon: { shape: 'primate', color: '#8a7a5a', faceColor: '#4a3a2a', bg1: '#e4dcc4', bg2: '#7a6a4a' } },
  { id: 'vervet-monkey', name: 'Vervet Monkey', sciName: 'Chlorocebus pygerythrus', category: 'primate', rarity: 'common',
    habitat: 'Riverine woodland, often around camps',
    fact: 'Vervet monkeys have distinct alarm calls for different predators - one for leopards, another for eagles, another for snakes.',
    icon: { shape: 'primate', color: '#9a9578', faceColor: '#1a1a1a', bg1: '#e6e2cc', bg2: '#8a8568' } },
  { id: 'rock-hyrax', name: 'Rock Hyrax', sciName: 'Procavia capensis', category: 'herbivore', rarity: 'uncommon',
    habitat: 'Rocky kopjes, basking in the sun in groups',
    fact: 'Despite looking like an overgrown guinea pig, the hyrax\'s closest living relative is the elephant.',
    icon: { shape: 'smallMammal', color: '#8a7a68', bands: false, bg1: '#e2dac8', bg2: '#7a6a58' } },
  { id: 'banded-mongoose', name: 'Banded Mongoose', sciName: 'Mungos mungo', category: 'herbivore', rarity: 'common',
    habitat: 'Old termite mounds, always in busy chattering packs',
    fact: 'Banded mongoose troops babysit cooperatively - adults take turns guarding all the pups while others forage.',
    icon: { shape: 'smallMammal', color: '#8a7658', bands: true, bg1: '#e2d6c0', bg2: '#7a6648' } },
  { id: 'aardvark', name: 'Aardvark', sciName: 'Orycteropus afer', category: 'herbivore', rarity: 'rare',
    habitat: 'Nocturnal burrower - an extremely rare daytime sighting',
    fact: 'Aardvarks can eat around 50,000 ants and termites in a single night using a sticky 30cm tongue.',
    icon: { shape: 'smallMammal', color: '#a89574', bg1: '#e8ddc4', bg2: '#988564' } },
  { id: 'pangolin', name: 'Ground Pangolin', sciName: 'Smutsia temminckii', category: 'herbivore', rarity: 'rare',
    habitat: 'Extremely elusive and nocturnal - a bucket-list sighting',
    fact: 'The pangolin is the only mammal covered entirely in scales, made of keratin - the same material as human fingernails.',
    icon: { shape: 'smallMammal', color: '#8a7a5f', bands: true, bg1: '#e2d6bc', bg2: '#7a6a4f' } },

  // ---- Reptiles ----
  { id: 'nile-crocodile', name: 'Nile Crocodile', sciName: 'Crocodylus niloticus', category: 'reptile', rarity: 'common',
    habitat: 'Mara River, famous for ambushing migration crossings',
    fact: 'The Mara River\'s crocodiles can live over 70 years and grow past 5 metres, timing their feeding around the annual migration crossings.',
    icon: { shape: 'reptileCroc', color: '#5a6a4a', bg1: '#d8dcc4', bg2: '#4a5a3a' } },
  { id: 'african-rock-python', name: 'African Rock Python', sciName: 'Python sebae', category: 'reptile', rarity: 'rare',
    habitat: 'Riverine thicket and rocky areas',
    fact: 'Africa\'s largest snake, the rock python can grow over 5 metres and kill prey as large as antelope by constriction.',
    icon: { shape: 'reptileSnake', color: '#8a7a4a', bg1: '#e2d8b8', bg2: '#7a6a3a' } },
  { id: 'nile-monitor', name: 'Nile Monitor', sciName: 'Varanus niloticus', category: 'reptile', rarity: 'uncommon',
    habitat: 'Riverbanks, an excellent swimmer and climber',
    fact: 'Nile monitors are notorious raiders of crocodile nests, digging up and eating the eggs.',
    icon: { shape: 'reptileLizard', color: '#5a6a58', pattern: 'spots', bg1: '#d8dcd0', bg2: '#4a5a48' } },

  // ---- Birds ----
  { id: 'ostrich', name: 'Common Ostrich', sciName: 'Struthio camelus', category: 'bird', rarity: 'common',
    habitat: 'Open plains, often in small groups',
    fact: 'The world\'s largest bird can\'t fly, but it can sprint at up to 70km/h - faster than any other bird on land.',
    icon: { shape: 'birdStand', color: '#2a2a2a', headColor: '#d9a24a', legColor: '#d9a24a', legLen: 40, neckLen: 40, accent: '#d9a24a', bg1: '#e6e0d0', bg2: '#3a3a3a' } },
  { id: 'secretarybird', name: 'Secretarybird', sciName: 'Sagittarius serpentarius', category: 'bird', rarity: 'uncommon',
    habitat: 'Grassland, striding on foot hunting snakes',
    fact: 'This striking raptor hunts on foot and kills snakes with rapid, forceful stamps that can exceed 5 times its own body weight in force.',
    icon: { shape: 'birdStand', color: '#d8d4c4', headColor: '#d8d4c4', legColor: '#c9a03f', legLen: 38, neckLen: 20, crest: true, accent: '#c9302c', bg1: '#e8e4d4', bg2: '#4a4a44' } },
  { id: 'grey-crowned-crane', name: 'Grey Crowned Crane', sciName: 'Balearica regulorum', category: 'bird', rarity: 'uncommon',
    habitat: 'Wetlands and grassland, Kenya\'s national bird',
    fact: 'Its golden crown of stiff feathers is unique among cranes, and pairs perform elaborate dancing displays to bond.',
    icon: { shape: 'birdStand', color: '#4a4a48', headColor: '#e8e4d8', legColor: '#2a2a2a', legLen: 32, neckLen: 30, crest: true, crestColor: '#e8b923', accent: '#c9302c', bg1: '#dcdcd0', bg2: '#3a3a38' } },
  { id: 'marabou-stork', name: 'Marabou Stork', sciName: 'Leptoptilos crumeniferus', category: 'bird', rarity: 'common',
    habitat: 'Near carcasses, water, and rubbish areas',
    fact: 'Nicknamed the "undertaker bird" for its cloak-like wings and bald head, it can have a wingspan of up to 3.2 metres.',
    icon: { shape: 'birdStand', color: '#3a3a3a', headColor: '#d99070', legColor: '#c9c4b4', legLen: 36, neckLen: 26, accent: '#c9c4b4', bg1: '#dcdcd4', bg2: '#3a3a3a' } },
  { id: 'saddle-billed-stork', name: 'Saddle-billed Stork', sciName: 'Ephippiorhynchus senegalensis', category: 'bird', rarity: 'uncommon',
    habitat: 'Wetlands and rivers, often solitary or in pairs',
    fact: 'One of Africa\'s tallest storks, its bill is boldly patterned red, black and yellow like a saddle.',
    icon: { shape: 'birdStand', color: '#1a1a2a', headColor: '#1a1a2a', legColor: '#c9302c', legLen: 38, neckLen: 32, accent: '#e8b923', bg1: '#dcdce4', bg2: '#2a2a3a' } },
  { id: 'hadada-ibis', name: 'Hadada Ibis', sciName: 'Bostrychia hagedash', category: 'bird', rarity: 'common',
    habitat: 'Lawns near camps and riverbanks',
    fact: 'Named after its loud "ha-ha-ha-de-dah" call, often the first and last sound heard each day in camp.',
    icon: { shape: 'birdStand', color: '#5a4a3a', headColor: '#5a4a3a', legColor: '#7a5a3a', legLen: 22, neckLen: 14, accent: '#6a5a3a', bg1: '#dcd4c4', bg2: '#4a3a2a' } },
  { id: 'hamerkop', name: 'Hamerkop', sciName: 'Scopus umbretta', category: 'bird', rarity: 'uncommon',
    habitat: 'Near water, builds enormous stick nests',
    fact: 'A single pair can build a nest of over 8,000 sticks strong enough to support a person\'s weight.',
    icon: { shape: 'birdStand', color: '#6a5a42', headColor: '#6a5a42', legColor: '#4a3a2a', legLen: 18, neckLen: 10, crest: true, crestColor: '#6a5a42', accent: '#4a3a2a', bg1: '#e0d8c4', bg2: '#5a4a32' } },
  { id: 'kori-bustard', name: 'Kori Bustard', sciName: 'Ardeotis kori', category: 'bird', rarity: 'uncommon',
    habitat: 'Open grassland, walking slowly and deliberately',
    fact: 'Believed to be the heaviest flying bird in the world, males can weigh up to 19kg.',
    icon: { shape: 'birdStand', color: '#b0a37e', headColor: '#e8e4d4', legColor: '#e8e4d4', legLen: 30, neckLen: 22, pattern: 'patches', accent: '#4a4a44', bg1: '#e8e2c8', bg2: '#9a8d68' } },
  { id: 'helmeted-guineafowl', name: 'Helmeted Guineafowl', sciName: 'Numida meleagris', category: 'bird', rarity: 'common',
    habitat: 'Grassland, in large noisy flocks',
    fact: 'Its plumage is covered in hundreds of small white polka-dots, giving rise to its nickname "the spotted hen".',
    icon: { shape: 'birdStand', color: '#3a3a44', headColor: '#c9302c', legColor: '#4a4a44', legLen: 16, neckLen: 8, pattern: 'patches', accent: '#e8b923', bg1: '#d8d8dc', bg2: '#2a2a34' } },
  { id: 'african-fish-eagle', name: 'African Fish Eagle', sciName: 'Haliaeetus vocifer', category: 'bird', rarity: 'common',
    habitat: 'Perched near rivers and lakes',
    fact: 'Its iconic ringing call is often called "the voice of Africa" and can carry for kilometres over water.',
    icon: { shape: 'birdPerch', color: '#3a3a3a', headColor: '#e8e4d4', hooked: true, accent: '#e8b923', bg1: '#dcdcd4', bg2: '#3a3a3a' } },
  { id: 'martial-eagle', name: 'Martial Eagle', sciName: 'Polemaetus bellicosus', category: 'bird', rarity: 'rare',
    habitat: 'Perched high in trees or soaring over the plains',
    fact: 'Africa\'s largest eagle is powerful enough to take down prey as large as a young antelope.',
    icon: { shape: 'birdPerch', color: '#6a5f4a', headColor: '#6a5f4a', hooked: true, pattern: 'patches', accent: '#3a3a3a', bg1: '#dcd6c4', bg2: '#5a4f3a' } },
  { id: 'bateleur', name: 'Bateleur', sciName: 'Terathopius ecaudatus', category: 'bird', rarity: 'uncommon',
    habitat: 'Soaring low over open plains',
    fact: 'French for "tightrope walker" - named for its acrobatic, rocking flight and near-tailless silhouette.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', headColor: '#c9302c', hooked: true, accent: '#c9302c', belly: '#c9302c', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'ruppells-vulture', name: "Rüppell's Griffon Vulture", sciName: 'Gyps rueppelli', category: 'bird', rarity: 'uncommon',
    habitat: 'Soaring in thermals, gathering fast at carcasses',
    fact: 'Recorded flying at over 11,000 metres, this is the highest-flying bird ever documented.',
    icon: { shape: 'birdPerch', color: '#a89878', headColor: '#d9c9a0', hooked: true, pattern: 'patches', accent: '#8a7a5a', bg1: '#e6ddc4', bg2: '#98876a' } },
  { id: 'lappet-faced-vulture', name: 'Lappet-faced Vulture', sciName: 'Torgos tracheliotos', category: 'bird', rarity: 'uncommon',
    habitat: 'Perched in flat-topped acacias near carcasses',
    fact: 'The largest and most powerful African vulture, dominant enough to displace other vultures from a kill.',
    icon: { shape: 'birdPerch', color: '#3a3a3a', headColor: '#c9302c', hooked: true, accent: '#4a4a44', bg1: '#dcdcd8', bg2: '#2a2a2a' } },
  { id: 'lilac-breasted-roller', name: 'Lilac-breasted Roller', sciName: 'Coracias caudatus', category: 'bird', rarity: 'common',
    habitat: 'Perched on low branches and fence posts',
    fact: 'Widely considered one of Africa\'s most beautiful birds, showing off up to eight different colours at once.',
    icon: { shape: 'birdPerch', color: '#7a9fc9', headColor: '#a892c9', accent: '#3aa8a0', belly: '#c9a0d0', bg1: '#e0e8f0', bg2: '#6a8fc0' } },
  { id: 'superb-starling', name: 'Superb Starling', sciName: 'Lamprotornis superbus', category: 'bird', rarity: 'common',
    habitat: 'Around camps and lodges, bold and inquisitive',
    fact: 'Its iridescent blue-green back and sharp orange belly make it one of the most photographed birds in East Africa.',
    icon: { shape: 'birdPerch', color: '#2a6a8a', pattern: 'iridescent', belly: '#d9822a', accent: '#1a1a1a', bg1: '#d8e6ea', bg2: '#1a5a7a' } },
  { id: 'little-bee-eater', name: 'Little Bee-eater', sciName: 'Merops pusillus', category: 'bird', rarity: 'common',
    habitat: 'Perched low near water, sallying for insects',
    fact: 'This tiny, vivid bird catches bees and wasps in flight, then rubs them on a branch to remove the sting before eating.',
    icon: { shape: 'birdPerch', color: '#8ab93a', headColor: '#d9a52a', accent: '#1a1a1a', belly: '#d9822a', bg1: '#e6efd0', bg2: '#78a72a' } },
  { id: 'grey-go-away-bird', name: 'Grey Go-away-bird', sciName: 'Crinifer concolor', category: 'bird', rarity: 'common',
    habitat: 'Woodland and camps, very vocal',
    fact: 'Named for its nasal "go-away" call, which - much to guides\' frustration - often warns wildlife of approaching vehicles.',
    icon: { shape: 'birdPerch', color: '#b8b4a8', crest: true, crestColor: '#b8b4a8', accent: '#4a4a44', bg1: '#e6e4dc', bg2: '#a8a498' } },
  { id: 'southern-ground-hornbill', name: 'Southern Ground Hornbill', sciName: 'Bucorvus leadbeateri', category: 'bird', rarity: 'uncommon',
    habitat: 'Walking in small groups across grassland',
    fact: 'These turkey-sized hornbills live in cooperative family groups and can live for 50-70 years.',
    icon: { shape: 'birdStand', color: '#1a1a1a', headColor: '#c9302c', legColor: '#1a1a1a', legLen: 26, neckLen: 12, accent: '#1a1a1a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'yellow-billed-hornbill', name: 'Yellow-billed Hornbill', sciName: 'Tockus flavirostris', category: 'bird', rarity: 'common',
    habitat: 'Woodland, hopping along the ground foraging',
    fact: 'Nicknamed the "flying banana" for its oversized curved yellow bill.',
    icon: { shape: 'birdPerch', color: '#6a5a48', headColor: '#6a5a48', hooked: true, accent: '#e8c93a', bg1: '#e2dccb', bg2: '#5a4a38' } },
  { id: 'egyptian-goose', name: 'Egyptian Goose', sciName: 'Alopochen aegyptiaca', category: 'bird', rarity: 'common',
    habitat: 'Riverbanks and marshes',
    fact: 'Despite its name, it\'s more closely related to shelducks than true geese, and was considered sacred in ancient Egypt.',
    icon: { shape: 'birdStand', color: '#c9a878', headColor: '#c9a878', legColor: '#d9822a', legLen: 14, neckLen: 8, pattern: 'patches', accent: '#8a5a2a', bg1: '#eee3c8', bg2: '#b89868' } },
  { id: 'long-tailed-widowbird', name: 'Long-tailed Widowbird', sciName: 'Euplectes progne', category: 'bird', rarity: 'common',
    habitat: 'Tall grassland, males displaying in breeding season',
    fact: 'Breeding males grow a tail up to half a metre long purely to impress females in slow, floating display flights.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', accent: '#c9302c', belly: '#1a1a1a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'pied-kingfisher', name: 'Pied Kingfisher', sciName: 'Ceryle rudis', category: 'bird', rarity: 'common',
    habitat: 'Hovering over rivers and lakes before diving',
    fact: 'One of the few kingfishers that can hover in place over water, sometimes for over a minute, before plunging for fish.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', headColor: '#1a1a1a', pattern: 'patches', accent: '#1a1a1a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'malachite-kingfisher', name: 'Malachite Kingfisher', sciName: 'Corythornis cristatus', category: 'bird', rarity: 'uncommon',
    habitat: 'Reeds along quiet water',
    fact: 'One of Africa\'s smallest kingfishers, its electric-blue back seems to glow in direct sunlight.',
    icon: { shape: 'birdPerch', color: '#1a8a9a', headColor: '#1a8a9a', crest: true, crestColor: '#1a8a9a', accent: '#c9302c', belly: '#d9822a', bg1: '#d0eef0', bg2: '#0a6a7a' } },
  { id: 'red-billed-oxpecker', name: 'Red-billed Oxpecker', sciName: 'Buphagus erythrorhynchus', category: 'bird', rarity: 'common',
    habitat: 'Riding on buffalo, giraffe and antelope',
    fact: 'It clings to large herbivores and feeds on the ticks and parasites living on their skin, sometimes to the point of keeping wounds open.',
    icon: { shape: 'birdPerch', color: '#8a7a58', accent: '#c9302c', bg1: '#e2d8c0', bg2: '#7a6a48' } },
  { id: 'crowned-lapwing', name: 'Crowned Lapwing', sciName: 'Vanellus coronatus', category: 'bird', rarity: 'common',
    habitat: 'Open short grassland and roadsides',
    fact: 'It defends its ground nest with loud alarm calls and dramatic broken-wing distraction displays.',
    icon: { shape: 'birdStand', color: '#8a7a68', headColor: '#8a7a68', legColor: '#d9822a', legLen: 20, neckLen: 10, crest: true, crestColor: '#e8e4d4', accent: '#1a1a1a', bg1: '#e2d8c4', bg2: '#7a6a58' } },
];

if (typeof window !== 'undefined') window.SPECIES = SPECIES;
if (typeof module !== 'undefined') module.exports = { SPECIES };
