// Masai Mara wildlife checklist data.
// category: predator | herbivore | primate | reptile | bird
// rarity: common | uncommon | rare  (rough guide, not scientific)

const SPECIES = [
  // ---- Big cats & predators ----
  { id: 'lion', name: 'Lion', sciName: 'Panthera leo', category: 'predator', rarity: 'common', big5: true,
    habitat: 'Open savanna, often resting in shade near the Mara River',
    fact: 'A pride\'s roar can be heard up to 8km away, and the Mara\'s prides are some of the largest in Africa, sometimes over 20 lions.',
    icon: { shape: 'quadruped', size: 'xl', color: '#c9963c', mane: true, maneColor: '#7a4a1e', tailTuft: true, bg1: '#f6e6bd', bg2: '#d8a94c' } },
  { id: 'leopard', name: 'Leopard', sciName: 'Panthera pardus', category: 'predator', rarity: 'uncommon', big5: true,
    habitat: 'Riverine forest and thick bush, often draped over tree branches',
    fact: 'Leopards can drag a kill twice their own body weight up into a tree to keep it safe from lions and hyenas.',
    icon: { shape: 'quadruped', size: 'l', color: '#d9a24a', pattern: 'spots', tailTuft: false, bg1: '#f2e2b8', bg2: '#c98f3a' } },
  { id: 'cheetah', name: 'Cheetah', sciName: 'Acinonyx jubatus', category: 'predator', rarity: 'uncommon',
    habitat: 'Open plains where it can use its speed',
    fact: 'The cheetah can accelerate from 0 to 100km/h in about three seconds - faster than most sports cars.',
    icon: { shape: 'quadruped', size: 'l', color: '#e0b262', pattern: 'spots', longNeck: true, bg1: '#f4e8c8', bg2: '#d8b25f' } },
  { id: 'spotted-hyena', name: 'Spotted Hyena', sciName: 'Crocuta crocuta', category: 'predator', rarity: 'common',
    habitat: 'Clans denning in old aardvark burrows across the plains',
    fact: 'Spotted hyenas are highly skilled hunters, not just scavengers - they make up to 95% of their own kills.',
    icon: { shape: 'quadruped', size: 'm', color: '#b8a184', pattern: 'patches', bg1: '#e8ddc8', bg2: '#a89577' } },
  { id: 'black-backed-jackal', name: 'Black-backed Jackal', sciName: 'Lupulella mesomelas', category: 'predator', rarity: 'common',
    habitat: 'Plains and woodland edges, often seen trotting alone at dawn',
    fact: 'Jackal pairs mate for life and both parents, plus older offspring, help raise each new litter of pups.',
    icon: { shape: 'quadruped', size: 's', color: '#b5793f', mane: true, maneColor: '#3a3a3a', bg1: '#eadfc4', bg2: '#a8783f' } },
  { id: 'bat-eared-fox', name: 'Bat-eared Fox', sciName: 'Otocyon megalotis', category: 'predator', rarity: 'uncommon',
    habitat: 'Short grass plains, usually in small family groups',
    fact: 'Its huge ears aren\'t just for hearing predators - they radiate heat and can detect the sound of insects moving underground.',
    icon: { shape: 'quadruped', size: 's', color: '#cbb48c', bg1: '#efe6cf', bg2: '#b8a37c' } },
  { id: 'african-wild-dog', name: 'African Wild Dog', sciName: 'Lycaon pictus', category: 'predator', rarity: 'rare',
    habitat: 'Wide-ranging packs, a rare and exciting sighting',
    fact: 'One of Africa\'s most endangered carnivores, wild dog packs hunt cooperatively with an astonishing 80% hunt success rate.',
    icon: { shape: 'quadruped', size: 'm', color: '#c9a878', pattern: 'patches', bg1: '#e8dcc2', bg2: '#b08f5c' } },
  { id: 'serval', name: 'Serval', sciName: 'Leptailurus serval', category: 'predator', rarity: 'rare',
    habitat: 'Tall grassland near water, mostly at dusk',
    fact: 'Relative to body size, the serval has the largest ears of any cat, letting it pinpoint rodents hidden deep in grass.',
    icon: { shape: 'quadruped', size: 's', color: '#e0b95f', pattern: 'spots', longNeck: true, bg1: '#f4ecc9', bg2: '#dcb85f' } },
  { id: 'caracal', name: 'Caracal', sciName: 'Caracal caracal', category: 'predator', rarity: 'rare',
    habitat: 'Rocky outcrops and thick cover, mostly nocturnal',
    fact: 'Caracals can leap over 3 metres straight up to swat birds out of the air.',
    icon: { shape: 'quadruped', size: 's', color: '#c9713f', bg1: '#ecd2b8', bg2: '#b8663a' } },
  { id: 'honey-badger', name: 'Honey Badger', sciName: 'Mellivora capensis', category: 'predator', rarity: 'rare',
    habitat: 'Widespread but rarely seen, often solitary and fearless',
    fact: 'Famous for its fearlessness, the honey badger is one of very few animals known to actively fend off lions.',
    icon: { shape: 'smallMammal', color: '#3a3a3a', twoTone: true, bg1: '#dcdcd4', bg2: '#8a8a82' } },

  // ---- Big herbivores ----
  { id: 'african-elephant', name: 'African Bush Elephant', sciName: 'Loxodonta africana', category: 'herbivore', rarity: 'common', big5: true,
    habitat: 'Woodland and riverbanks, moving in tight-knit family herds',
    fact: 'Elephants communicate over several kilometres using infrasound rumbles too low for humans to hear.',
    icon: { shape: 'elephant', color: '#8f8a80', tusks: true, bg1: '#e4ded2', bg2: '#8f8a80' } },
  { id: 'black-rhino', name: 'Black Rhinoceros', sciName: 'Diceros bicornis', category: 'herbivore', rarity: 'rare', big5: true,
    habitat: 'Dense bush, critically endangered - a special sighting',
    fact: 'Despite the name, black rhinos are grey - the name distinguishes their pointed lip (for browsing) from the white rhino\'s wide, flat lip.',
    icon: { shape: 'rhino', color: '#918070', bg1: '#e2d8c8', bg2: '#8a7a68' } },
  { id: 'cape-buffalo', name: 'African (Cape) Buffalo', sciName: 'Syncerus caffer', category: 'herbivore', rarity: 'common', big5: true,
    habitat: 'Large herds on the plains, never far from water',
    fact: 'Nicknamed "black death" by hunters, buffalo are considered the most dangerous of the Big Five due to unpredictable charges.',
    icon: { shape: 'quadruped', size: 'l', color: '#4a453e', horn: 'ringed', hornColor: '#2a2620', bg1: '#d8d4c8', bg2: '#4a453e' } },
  { id: 'hippopotamus', name: 'Hippopotamus', sciName: 'Hippopotamus amphibius', category: 'herbivore', rarity: 'common',
    habitat: 'Pods wallowing in the Mara River and Talek River',
    fact: 'Hippos secrete a natural reddish oily substance often called "blood sweat" that acts as sunscreen and an antibiotic.',
    icon: { shape: 'hippo', color: '#8a8577', bg1: '#dcd8c8', bg2: '#7a7568' } },
  { id: 'giraffe', name: 'Masai Giraffe', sciName: 'Giraffa tippelskirchi', category: 'herbivore', rarity: 'common',
    habitat: 'Acacia woodland, browsing on treetops',
    fact: 'A giraffe\'s heart weighs around 11kg and generates roughly double the blood pressure of a human to pump blood up that long neck.',
    icon: { shape: 'quadruped', size: 'l', giraffe: true, color: '#d9a94f', pattern: 'patches', bg1: '#f2e4bd', bg2: '#c99b3f' } },
  { id: 'common-zebra', name: 'Plains Zebra', sciName: 'Equus quagga', category: 'herbivore', rarity: 'common',
    habitat: 'Huge herds across the plains, mixing with wildebeest',
    fact: 'Every zebra\'s stripe pattern is as unique as a human fingerprint, helping foals recognise their own mother in a herd.',
    icon: { shape: 'quadruped', size: 'm', color: '#f2efe6', pattern: 'stripes', mane: true, maneColor: '#2b2b2b', bg1: '#f2efe6', bg2: '#3a3a3a' } },
  { id: 'blue-wildebeest', name: 'Blue Wildebeest', sciName: 'Connochaetes taurinus', category: 'herbivore', rarity: 'common',
    habitat: 'The star of the Great Migration, in herds of thousands',
    fact: 'Over 1.5 million wildebeest cross the Mara River each year in one of the largest land mammal migrations on Earth.',
    icon: { shape: 'quadruped', size: 'm', color: '#5a5a52', mane: true, maneColor: '#1e1e1a', horn: 'lyre', hornColor: '#2a2a2a', bg1: '#d8d6ca', bg2: '#4a4a44' } },
  { id: 'impala', name: 'Impala', sciName: 'Aepyceros melampus', category: 'herbivore', rarity: 'common',
    habitat: 'Woodland edges, in large mixed or bachelor herds',
    fact: 'An impala can leap 3 metres high and 10 metres in a single bound to escape predators.',
    icon: { shape: 'quadruped', size: 's', color: '#c9873f', horn: 'lyre', bg1: '#eeddc0', bg2: '#b87d3a' } },
  { id: 'thomsons-gazelle', name: "Thomson's Gazelle", sciName: 'Eudorcas thomsonii', category: 'herbivore', rarity: 'common',
    habitat: 'Short grass plains, constantly flicking its tail',
    fact: '"Tommies" stot - bouncing stiff-legged into the air - to signal to predators that they\'ve been spotted and a chase is pointless.',
    icon: { shape: 'quadruped', size: 's', color: '#d9b978', horn: 'straight', bg1: '#f2e8cc', bg2: '#c9a866' } },
  { id: 'grants-gazelle', name: "Grant's Gazelle", sciName: 'Nanger granti', category: 'herbivore', rarity: 'common',
    habitat: 'Drier open plains, larger than the Thomson\'s gazelle',
    fact: 'Grant\'s gazelles can go for extended periods without drinking water, getting most of their moisture from plants.',
    icon: { shape: 'quadruped', size: 's', color: '#e2cf9e', horn: 'lyre', bg1: '#f4ecd4', bg2: '#d2ba82' } },
  { id: 'topi', name: 'Topi', sciName: 'Damaliscus lunatus jimela', category: 'herbivore', rarity: 'common',
    habitat: 'Grassy plains, often standing sentinel on old termite mounds',
    fact: 'Topi are considered one of the fastest antelope in Africa and often stand atop termite mounds to watch for predators.',
    icon: { shape: 'quadruped', size: 'm', color: '#7a4a3a', pattern: 'patches', horn: 'lyre', bg1: '#dcc4ac', bg2: '#6a3f30' } },
  { id: 'cokes-hartebeest', name: "Coke's Hartebeest", sciName: 'Alcelaphus buselaphus cokii', category: 'herbivore', rarity: 'common',
    habitat: 'Open plains, recognisable by its long face and sloped back',
    fact: 'Locally called "Kongoni", its oddly elongated skull houses large sinuses thought to help with cooling.',
    icon: { shape: 'quadruped', size: 'm', color: '#b98a56', horn: 'lyre', bg1: '#ecd8ba', bg2: '#a97a48' } },
  { id: 'waterbuck', name: 'Waterbuck', sciName: 'Kobus ellipsiprymnus', category: 'herbivore', rarity: 'common',
    habitat: 'Always close to rivers and marshes',
    fact: 'Waterbuck have a natural oily secretion in their coat with a musky odour that some believe deters predators from eating them.',
    icon: { shape: 'quadruped', size: 'm', color: '#786858', horn: 'ringed', bg1: '#dcd4c4', bg2: '#68584a' } },
  { id: 'eland', name: 'Common Eland', sciName: 'Taurotragus oryx', category: 'herbivore', rarity: 'uncommon',
    habitat: 'Open plains and woodland, Africa\'s largest antelope',
    fact: 'Despite weighing up to 900kg, elands are excellent jumpers and can clear fences over 2.5 metres tall.',
    icon: { shape: 'quadruped', size: 'l', color: '#b39a78', horn: 'spiral', bg1: '#e8dcc4', bg2: '#a38a68' } },
  { id: 'kudu', name: 'Greater Kudu', sciName: 'Tragelaphus strepsiceros', category: 'herbivore', rarity: 'rare',
    habitat: 'Thick bush and rocky hillsides',
    fact: 'The male\'s spectacular spiralling horns can grow to over 1.2 metres and make one and a half graceful turns.',
    icon: { shape: 'quadruped', size: 'm', color: '#8a8272', pattern: 'stripes', horn: 'spiral', bg1: '#d8d4c4', bg2: '#7a7262' } },
  { id: 'dik-dik', name: "Kirk's Dik-dik", sciName: 'Madoqua kirkii', category: 'herbivore', rarity: 'uncommon',
    habitat: 'Dense thicket, seen darting in monogamous pairs',
    fact: 'One of the smallest antelope in the world, standing just 40cm tall, and it mates for life.',
    icon: { shape: 'quadruped', size: 's', color: '#c9a878', horn: 'short', bg1: '#eeddc0', bg2: '#b8935f' } },
  { id: 'warthog', name: 'Common Warthog', sciName: 'Phacochoerus africanus', category: 'herbivore', rarity: 'common',
    habitat: 'Open grassland, trotting with tail held straight up',
    fact: 'Warthogs run backwards into burrows so they can face outward and defend themselves with their tusks.',
    icon: { shape: 'quadruped', size: 'm', color: '#5a534a', tusks: true, mane: true, maneColor: '#2a271f', tailTuft: true, bg1: '#d8d2c4', bg2: '#4a453e' } },
  { id: 'olive-baboon', name: 'Olive Baboon', sciName: 'Papio anubis', category: 'primate', rarity: 'common',
    habitat: 'Troops of dozens, active on the ground and in trees',
    fact: 'Baboon troops have a strict social hierarchy, and lower-ranking members often groom higher-ranking ones to build alliances.',
    icon: { shape: 'primate', color: '#8a7a5a', faceColor: '#4a3a2a', bg1: '#e4dcc4', bg2: '#7a6a4a' } },
  { id: 'vervet-monkey', name: 'Vervet Monkey', sciName: 'Chlorocebus pygerythrus', category: 'primate', rarity: 'common',
    habitat: 'Riverine woodland, often around camps',
    fact: 'Vervet monkeys have distinct alarm calls for different predators - one for leopards, another for eagles, another for snakes.',
    icon: { shape: 'primate', color: '#9a9578', faceColor: '#1a1a1a', bg1: '#e6e2cc', bg2: '#8a8568' } },
  { id: 'rock-hyrax', name: 'Rock Hyrax', sciName: 'Procavia capensis', category: 'herbivore', rarity: 'uncommon',
    habitat: 'Rocky kopjes, basking in the sun in groups',
    fact: 'Despite looking like an overgrown guinea pig, the hyrax\'s closest living relative is the elephant.',
    icon: { shape: 'smallMammal', color: '#8a7a68', bands: false, bg1: '#e2dac8', bg2: '#7a6a58' } },
  { id: 'banded-mongoose', name: 'Banded Mongoose', sciName: 'Mungos mungo', category: 'herbivore', rarity: 'common',
    habitat: 'Old termite mounds, always in busy chattering packs',
    fact: 'Banded mongoose troops babysit cooperatively - adults take turns guarding all the pups while others forage.',
    icon: { shape: 'smallMammal', color: '#8a7658', bands: true, bg1: '#e2d6c0', bg2: '#7a6648' } },
  { id: 'aardvark', name: 'Aardvark', sciName: 'Orycteropus afer', category: 'herbivore', rarity: 'rare',
    habitat: 'Nocturnal burrower - an extremely rare daytime sighting',
    fact: 'Aardvarks can eat around 50,000 ants and termites in a single night using a sticky 30cm tongue.',
    icon: { shape: 'smallMammal', color: '#a89574', bg1: '#e8ddc4', bg2: '#988564' } },
  { id: 'pangolin', name: 'Ground Pangolin', sciName: 'Smutsia temminckii', category: 'herbivore', rarity: 'rare',
    habitat: 'Extremely elusive and nocturnal - a bucket-list sighting',
    fact: 'The pangolin is the only mammal covered entirely in scales, made of keratin - the same material as human fingernails.',
    icon: { shape: 'smallMammal', color: '#8a7a5f', bands: true, bg1: '#e2d6bc', bg2: '#7a6a4f' } },

  // ---- Reptiles ----
  { id: 'nile-crocodile', name: 'Nile Crocodile', sciName: 'Crocodylus niloticus', category: 'reptile', rarity: 'common',
    habitat: 'Mara River, famous for ambushing migration crossings',
    fact: 'The Mara River\'s crocodiles can live over 70 years and grow past 5 metres, timing their feeding around the annual migration crossings.',
    icon: { shape: 'reptileCroc', color: '#5a6a4a', bg1: '#d8dcc4', bg2: '#4a5a3a' } },
  { id: 'african-rock-python', name: 'African Rock Python', sciName: 'Python sebae', category: 'reptile', rarity: 'rare',
    habitat: 'Riverine thicket and rocky areas',
    fact: 'Africa\'s largest snake, the rock python can grow over 5 metres and kill prey as large as antelope by constriction.',
    icon: { shape: 'reptileSnake', color: '#8a7a4a', bg1: '#e2d8b8', bg2: '#7a6a3a' } },
  { id: 'nile-monitor', name: 'Nile Monitor', sciName: 'Varanus niloticus', category: 'reptile', rarity: 'uncommon',
    habitat: 'Riverbanks, an excellent swimmer and climber',
    fact: 'Nile monitors are notorious raiders of crocodile nests, digging up and eating the eggs.',
    icon: { shape: 'reptileLizard', color: '#5a6a58', pattern: 'spots', bg1: '#d8dcd0', bg2: '#4a5a48' } },

  // ---- Birds ----
  { id: 'ostrich', name: 'Common Ostrich', sciName: 'Struthio camelus', category: 'bird', rarity: 'common',
    habitat: 'Open plains, often in small groups',
    fact: 'The world\'s largest bird can\'t fly, but it can sprint at up to 70km/h - faster than any other bird on land.',
    icon: { shape: 'birdStand', color: '#2a2a2a', headColor: '#d9a24a', legColor: '#d9a24a', legLen: 40, neckLen: 40, accent: '#d9a24a', bg1: '#e6e0d0', bg2: '#3a3a3a' } },
  { id: 'secretarybird', name: 'Secretarybird', sciName: 'Sagittarius serpentarius', category: 'bird', rarity: 'uncommon',
    habitat: 'Grassland, striding on foot hunting snakes',
    fact: 'This striking raptor hunts on foot and kills snakes with rapid, forceful stamps that can exceed 5 times its own body weight in force.',
    icon: { shape: 'birdStand', color: '#d8d4c4', headColor: '#d8d4c4', legColor: '#c9a03f', legLen: 38, neckLen: 20, crest: true, accent: '#c9302c', bg1: '#e8e4d4', bg2: '#4a4a44' } },
  { id: 'grey-crowned-crane', name: 'Grey Crowned Crane', sciName: 'Balearica regulorum', category: 'bird', rarity: 'uncommon',
    habitat: 'Wetlands and grassland, Kenya\'s national bird',
    fact: 'Its golden crown of stiff feathers is unique among cranes, and pairs perform elaborate dancing displays to bond.',
    icon: { shape: 'birdStand', color: '#4a4a48', headColor: '#e8e4d8', legColor: '#2a2a2a', legLen: 32, neckLen: 30, crest: true, crestColor: '#e8b923', accent: '#c9302c', bg1: '#dcdcd0', bg2: '#3a3a38' } },
  { id: 'marabou-stork', name: 'Marabou Stork', sciName: 'Leptoptilos crumeniferus', category: 'bird', rarity: 'common',
    habitat: 'Near carcasses, water, and rubbish areas',
    fact: 'Nicknamed the "undertaker bird" for its cloak-like wings and bald head, it can have a wingspan of up to 3.2 metres.',
    icon: { shape: 'birdStand', color: '#3a3a3a', headColor: '#d99070', legColor: '#c9c4b4', legLen: 36, neckLen: 26, accent: '#c9c4b4', bg1: '#dcdcd4', bg2: '#3a3a3a' } },
  { id: 'saddle-billed-stork', name: 'Saddle-billed Stork', sciName: 'Ephippiorhynchus senegalensis', category: 'bird', rarity: 'uncommon',
    habitat: 'Wetlands and rivers, often solitary or in pairs',
    fact: 'One of Africa\'s tallest storks, its bill is boldly patterned red, black and yellow like a saddle.',
    icon: { shape: 'birdStand', color: '#1a1a2a', headColor: '#1a1a2a', legColor: '#c9302c', legLen: 38, neckLen: 32, accent: '#e8b923', bg1: '#dcdce4', bg2: '#2a2a3a' } },
  { id: 'hadada-ibis', name: 'Hadada Ibis', sciName: 'Bostrychia hagedash', category: 'bird', rarity: 'common',
    habitat: 'Lawns near camps and riverbanks',
    fact: 'Named after its loud "ha-ha-ha-de-dah" call, often the first and last sound heard each day in camp.',
    icon: { shape: 'birdStand', color: '#5a4a3a', headColor: '#5a4a3a', legColor: '#7a5a3a', legLen: 22, neckLen: 14, accent: '#6a5a3a', bg1: '#dcd4c4', bg2: '#4a3a2a' } },
  { id: 'hamerkop', name: 'Hamerkop', sciName: 'Scopus umbretta', category: 'bird', rarity: 'uncommon',
    habitat: 'Near water, builds enormous stick nests',
    fact: 'A single pair can build a nest of over 8,000 sticks strong enough to support a person\'s weight.',
    icon: { shape: 'birdStand', color: '#6a5a42', headColor: '#6a5a42', legColor: '#4a3a2a', legLen: 18, neckLen: 10, crest: true, crestColor: '#6a5a42', accent: '#4a3a2a', bg1: '#e0d8c4', bg2: '#5a4a32' } },
  { id: 'kori-bustard', name: 'Kori Bustard', sciName: 'Ardeotis kori', category: 'bird', rarity: 'uncommon',
    habitat: 'Open grassland, walking slowly and deliberately',
    fact: 'Believed to be the heaviest flying bird in the world, males can weigh up to 19kg.',
    icon: { shape: 'birdStand', color: '#b0a37e', headColor: '#e8e4d4', legColor: '#e8e4d4', legLen: 30, neckLen: 22, pattern: 'patches', accent: '#4a4a44', bg1: '#e8e2c8', bg2: '#9a8d68' } },
  { id: 'helmeted-guineafowl', name: 'Helmeted Guineafowl', sciName: 'Numida meleagris', category: 'bird', rarity: 'common',
    habitat: 'Grassland, in large noisy flocks',
    fact: 'Its plumage is covered in hundreds of small white polka-dots, giving rise to its nickname "the spotted hen".',
    icon: { shape: 'birdStand', color: '#3a3a44', headColor: '#c9302c', legColor: '#4a4a44', legLen: 16, neckLen: 8, pattern: 'patches', accent: '#e8b923', bg1: '#d8d8dc', bg2: '#2a2a34' } },
  { id: 'african-fish-eagle', name: 'African Fish Eagle', sciName: 'Haliaeetus vocifer', category: 'bird', rarity: 'common',
    habitat: 'Perched near rivers and lakes',
    fact: 'Its iconic ringing call is often called "the voice of Africa" and can carry for kilometres over water.',
    icon: { shape: 'birdPerch', color: '#3a3a3a', headColor: '#e8e4d4', hooked: true, accent: '#e8b923', bg1: '#dcdcd4', bg2: '#3a3a3a' } },
  { id: 'martial-eagle', name: 'Martial Eagle', sciName: 'Polemaetus bellicosus', category: 'bird', rarity: 'rare',
    habitat: 'Perched high in trees or soaring over the plains',
    fact: 'Africa\'s largest eagle is powerful enough to take down prey as large as a young antelope.',
    icon: { shape: 'birdPerch', color: '#6a5f4a', headColor: '#6a5f4a', hooked: true, pattern: 'patches', accent: '#3a3a3a', bg1: '#dcd6c4', bg2: '#5a4f3a' } },
  { id: 'bateleur', name: 'Bateleur', sciName: 'Terathopius ecaudatus', category: 'bird', rarity: 'uncommon',
    habitat: 'Soaring low over open plains',
    fact: 'French for "tightrope walker" - named for its acrobatic, rocking flight and near-tailless silhouette.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', headColor: '#c9302c', hooked: true, accent: '#c9302c', belly: '#c9302c', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'ruppells-vulture', name: "Rüppell's Griffon Vulture", sciName: 'Gyps rueppelli', category: 'bird', rarity: 'uncommon',
    habitat: 'Soaring in thermals, gathering fast at carcasses',
    fact: 'Recorded flying at over 11,000 metres, this is the highest-flying bird ever documented.',
    icon: { shape: 'birdPerch', color: '#a89878', headColor: '#d9c9a0', hooked: true, pattern: 'patches', accent: '#8a7a5a', bg1: '#e6ddc4', bg2: '#98876a' } },
  { id: 'lappet-faced-vulture', name: 'Lappet-faced Vulture', sciName: 'Torgos tracheliotos', category: 'bird', rarity: 'uncommon',
    habitat: 'Perched in flat-topped acacias near carcasses',
    fact: 'The largest and most powerful African vulture, dominant enough to displace other vultures from a kill.',
    icon: { shape: 'birdPerch', color: '#3a3a3a', headColor: '#c9302c', hooked: true, accent: '#4a4a44', bg1: '#dcdcd8', bg2: '#2a2a2a' } },
  { id: 'lilac-breasted-roller', name: 'Lilac-breasted Roller', sciName: 'Coracias caudatus', category: 'bird', rarity: 'common',
    habitat: 'Perched on low branches and fence posts',
    fact: 'Widely considered one of Africa\'s most beautiful birds, showing off up to eight different colours at once.',
    icon: { shape: 'birdPerch', color: '#7a9fc9', headColor: '#a892c9', accent: '#3aa8a0', belly: '#c9a0d0', bg1: '#e0e8f0', bg2: '#6a8fc0' } },
  { id: 'superb-starling', name: 'Superb Starling', sciName: 'Lamprotornis superbus', category: 'bird', rarity: 'common',
    habitat: 'Around camps and lodges, bold and inquisitive',
    fact: 'Its iridescent blue-green back and sharp orange belly make it one of the most photographed birds in East Africa.',
    icon: { shape: 'birdPerch', color: '#2a6a8a', pattern: 'iridescent', belly: '#d9822a', accent: '#1a1a1a', bg1: '#d8e6ea', bg2: '#1a5a7a' } },
  { id: 'little-bee-eater', name: 'Little Bee-eater', sciName: 'Merops pusillus', category: 'bird', rarity: 'common',
    habitat: 'Perched low near water, sallying for insects',
    fact: 'This tiny, vivid bird catches bees and wasps in flight, then rubs them on a branch to remove the sting before eating.',
    icon: { shape: 'birdPerch', color: '#8ab93a', headColor: '#d9a52a', accent: '#1a1a1a', belly: '#d9822a', bg1: '#e6efd0', bg2: '#78a72a' } },
  { id: 'grey-go-away-bird', name: 'Grey Go-away-bird', sciName: 'Crinifer concolor', category: 'bird', rarity: 'common',
    habitat: 'Woodland and camps, very vocal',
    fact: 'Named for its nasal "go-away" call, which - much to guides\' frustration - often warns wildlife of approaching vehicles.',
    icon: { shape: 'birdPerch', color: '#b8b4a8', crest: true, crestColor: '#b8b4a8', accent: '#4a4a44', bg1: '#e6e4dc', bg2: '#a8a498' } },
  { id: 'southern-ground-hornbill', name: 'Southern Ground Hornbill', sciName: 'Bucorvus leadbeateri', category: 'bird', rarity: 'uncommon',
    habitat: 'Walking in small groups across grassland',
    fact: 'These turkey-sized hornbills live in cooperative family groups and can live for 50-70 years.',
    icon: { shape: 'birdStand', color: '#1a1a1a', headColor: '#c9302c', legColor: '#1a1a1a', legLen: 26, neckLen: 12, accent: '#1a1a1a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'yellow-billed-hornbill', name: 'Yellow-billed Hornbill', sciName: 'Tockus flavirostris', category: 'bird', rarity: 'common',
    habitat: 'Woodland, hopping along the ground foraging',
    fact: 'Nicknamed the "flying banana" for its oversized curved yellow bill.',
    icon: { shape: 'birdPerch', color: '#6a5a48', headColor: '#6a5a48', hooked: true, accent: '#e8c93a', bg1: '#e2dccb', bg2: '#5a4a38' } },
  { id: 'egyptian-goose', name: 'Egyptian Goose', sciName: 'Alopochen aegyptiaca', category: 'bird', rarity: 'common',
    habitat: 'Riverbanks and marshes',
    fact: 'Despite its name, it\'s more closely related to shelducks than true geese, and was considered sacred in ancient Egypt.',
    icon: { shape: 'birdStand', color: '#c9a878', headColor: '#c9a878', legColor: '#d9822a', legLen: 14, neckLen: 8, pattern: 'patches', accent: '#8a5a2a', bg1: '#eee3c8', bg2: '#b89868' } },
  { id: 'long-tailed-widowbird', name: 'Long-tailed Widowbird', sciName: 'Euplectes progne', category: 'bird', rarity: 'common',
    habitat: 'Tall grassland, males displaying in breeding season',
    fact: 'Breeding males grow a tail up to half a metre long purely to impress females in slow, floating display flights.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', accent: '#c9302c', belly: '#1a1a1a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'pied-kingfisher', name: 'Pied Kingfisher', sciName: 'Ceryle rudis', category: 'bird', rarity: 'common',
    habitat: 'Hovering over rivers and lakes before diving',
    fact: 'One of the few kingfishers that can hover in place over water, sometimes for over a minute, before plunging for fish.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', headColor: '#1a1a1a', pattern: 'patches', accent: '#1a1a1a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'malachite-kingfisher', name: 'Malachite Kingfisher', sciName: 'Corythornis cristatus', category: 'bird', rarity: 'uncommon',
    habitat: 'Reeds along quiet water',
    fact: 'One of Africa\'s smallest kingfishers, its electric-blue back seems to glow in direct sunlight.',
    icon: { shape: 'birdPerch', color: '#1a8a9a', headColor: '#1a8a9a', crest: true, crestColor: '#1a8a9a', accent: '#c9302c', belly: '#d9822a', bg1: '#d0eef0', bg2: '#0a6a7a' } },
  { id: 'red-billed-oxpecker', name: 'Red-billed Oxpecker', sciName: 'Buphagus erythrorhynchus', category: 'bird', rarity: 'common',
    habitat: 'Riding on buffalo, giraffe and antelope',
    fact: 'It clings to large herbivores and feeds on the ticks and parasites living on their skin, sometimes to the point of keeping wounds open.',
    icon: { shape: 'birdPerch', color: '#8a7a58', accent: '#c9302c', bg1: '#e2d8c0', bg2: '#7a6a48' } },
  { id: 'crowned-lapwing', name: 'Crowned Lapwing', sciName: 'Vanellus coronatus', category: 'bird', rarity: 'common',
    habitat: 'Open short grassland and roadsides',
    fact: 'It defends its ground nest with loud alarm calls and dramatic broken-wing distraction displays.',
    icon: { shape: 'birdStand', color: '#8a7a68', headColor: '#8a7a68', legColor: '#d9822a', legLen: 20, neckLen: 10, crest: true, crestColor: '#e8e4d4', accent: '#1a1a1a', bg1: '#e2d8c4', bg2: '#7a6a58' } },

  // ---- More birds ----
  { id: 'grey-heron', name: 'Grey Heron', sciName: 'Ardea cinerea', category: 'bird', rarity: 'common',
    habitat: 'Riverbanks and marshes, standing motionless before striking',
    fact: 'A grey heron can stand frozen for several minutes waiting for a fish, then strike with its bill in a fraction of a second.',
    icon: { shape: 'birdStand', color: '#8a97a0', headColor: '#e2e0d6', legColor: '#5a6068', legLen: 34, neckLen: 30, accent: '#e0a83a', bg1: '#dfe3e0', bg2: '#6a7880' } },
  { id: 'black-headed-heron', name: 'Black-headed Heron', sciName: 'Ardea melanocephala', category: 'bird', rarity: 'common',
    habitat: 'Grassland as often as water, hunting rodents and insects',
    fact: 'Unlike most herons, it hunts as much on dry grassland for rodents and insects as it does in water.',
    icon: { shape: 'birdStand', color: '#dcd8ca', headColor: '#1a1a1a', legColor: '#3a3a3a', legLen: 32, neckLen: 28, accent: '#5a4a3a', bg1: '#e6e2d4', bg2: '#c9c4b4' } },
  { id: 'great-egret', name: 'Great (Yellow-billed) Egret', sciName: 'Ardea alba', category: 'bird', rarity: 'common',
    habitat: 'Wetland margins and riverbanks',
    fact: 'In breeding season it grows long, delicate plumes down its back once so prized by the fashion trade that hunting them for hats nearly wiped the species out.',
    icon: { shape: 'birdStand', color: '#f0ece0', headColor: '#f0ece0', legColor: '#2a2a2a', legLen: 34, neckLen: 32, accent: '#e0a83a', bg1: '#eae6da', bg2: '#c9c4b0' } },
  { id: 'cattle-egret', name: 'Cattle Egret', sciName: 'Bubulcus ibis', category: 'bird', rarity: 'common',
    habitat: 'Always close to buffalo, elephant, or livestock',
    fact: 'It follows large grazing animals to snap up insects flushed from the grass by their feet, an easy meal it rarely misses.',
    icon: { shape: 'birdStand', color: '#f2ece0', headColor: '#e8c988', legColor: '#e0c060', legLen: 20, neckLen: 14, accent: '#d9822a', bg1: '#eee7d6', bg2: '#c9c0a0' } },
  { id: 'sacred-ibis', name: 'African Sacred Ibis', sciName: 'Threskiornis aethiopicus', category: 'bird', rarity: 'common',
    habitat: 'Wetlands, floodplains and rubbish tips',
    fact: 'It was mummified and worshipped as sacred by the ancient Egyptians, who associated it with the god Thoth.',
    icon: { shape: 'birdStand', color: '#f0ece0', headColor: '#1a1a1a', legColor: '#1a1a1a', legLen: 26, neckLen: 20, accent: '#1a1a1a', bg1: '#e8e4d4', bg2: '#3a3a3a' } },
  { id: 'glossy-ibis', name: 'Glossy Ibis', sciName: 'Plegadis falcinellus', category: 'bird', rarity: 'uncommon',
    habitat: 'Marshes and flooded grassland',
    fact: 'In good light its dark plumage flashes an iridescent bronze-green and purple, one of the most widespread birds in the world.',
    icon: { shape: 'birdStand', color: '#5a3a4a', headColor: '#5a3a4a', legColor: '#3a2a3a', legLen: 24, neckLen: 22, accent: '#3a2a3a', bg1: '#dccbd4', bg2: '#4a2a3a' } },
  { id: 'african-openbill', name: 'African Openbill', sciName: 'Anastomus lamelligerus', category: 'bird', rarity: 'uncommon',
    habitat: 'Marshes and lake edges, feeding on snails',
    fact: 'Its bill has a permanent gap between the mandibles, perfectly shaped for winkling snails out of their shells.',
    icon: { shape: 'birdStand', color: '#2a2a2a', headColor: '#2a2a2a', legColor: '#3a3a3a', legLen: 26, neckLen: 20, accent: '#4a4a44', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'yellow-billed-stork', name: 'Yellow-billed Stork', sciName: 'Mycteria ibis', category: 'bird', rarity: 'common',
    habitat: 'Shallow water, sweeping its bill side to side to feel for fish',
    fact: 'It hunts by feel, not sight - sweeping its half-open bill through the water and snapping shut in as little as 25 milliseconds when it touches a fish.',
    icon: { shape: 'birdStand', color: '#f2e8d8', headColor: '#c9302c', legColor: '#d9302c', legLen: 34, neckLen: 28, accent: '#e8b923', bg1: '#eee6d4', bg2: '#c9bfa0' } },
  { id: 'woolly-necked-stork', name: 'Woolly-necked Stork', sciName: 'Ciconia episcopus', category: 'bird', rarity: 'uncommon',
    habitat: 'Wetlands and open woodland, usually alone or in pairs',
    fact: 'Named for the soft, fluffy white feathers around its neck, in sharp contrast to its glossy black cap.',
    icon: { shape: 'birdStand', color: '#1a1a1a', headColor: '#f0ece0', legColor: '#c9302c', legLen: 32, neckLen: 24, accent: '#c9302c', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'spur-winged-goose', name: 'Spur-winged Goose', sciName: 'Plectropterus gambensis', category: 'bird', rarity: 'common',
    habitat: 'Wetlands and floodplains, often in large flocks',
    fact: 'Africa\'s largest waterfowl, it carries a sharp spur on the bend of each wing used in territorial fights.',
    icon: { shape: 'birdStand', color: '#1a1a1a', headColor: '#c9c4b4', legColor: '#8a5a2a', legLen: 14, neckLen: 8, pattern: 'patches', accent: '#8a5a2a', bg1: '#dcdcd4', bg2: '#2a2a2a' } },
  { id: 'white-faced-whistling-duck', name: 'White-faced Whistling Duck', sciName: 'Dendrocygna viduata', category: 'bird', rarity: 'common',
    habitat: 'Lakes and lagoons, in tightly packed noisy flocks',
    fact: 'True to its name, it communicates with a constant high, whistling call, even in flight.',
    icon: { shape: 'birdStand', color: '#8a6a4a', headColor: '#f0ece0', legColor: '#2a2a2a', legLen: 14, neckLen: 10, accent: '#2a2a2a', bg1: '#e6dcc8', bg2: '#7a5a3a' } },
  { id: 'african-darter', name: 'African Darter', sciName: 'Anhinga rufa', category: 'bird', rarity: 'uncommon',
    habitat: 'Rivers and lakes, swimming with just its head above water',
    fact: 'Nicknamed the "snakebird" for the way it swims almost fully submerged, its thin neck weaving like a snake above the surface.',
    icon: { shape: 'birdStand', color: '#2a2a2a', headColor: '#8a5a3a', legColor: '#2a2a2a', legLen: 16, neckLen: 34, accent: '#2a2a2a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'reed-cormorant', name: 'Reed (Long-tailed) Cormorant', sciName: 'Microcarbo africanus', category: 'bird', rarity: 'common',
    habitat: 'Perched on snags over the river, wings spread to dry',
    fact: 'Its feathers aren\'t fully waterproof, so after diving for fish it must perch with wings outstretched to dry off in the sun.',
    icon: { shape: 'birdStand', color: '#1a1a1a', headColor: '#1a1a1a', legColor: '#1a1a1a', legLen: 14, neckLen: 14, accent: '#1a1a1a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'african-jacana', name: 'African Jacana', sciName: 'Actophilornis africanus', category: 'bird', rarity: 'common',
    habitat: 'Lily-covered lagoons, walking on floating vegetation',
    fact: 'Nicknamed the "Jesus bird" for appearing to walk on water, thanks to its enormously long toes that spread its weight across lily pads.',
    icon: { shape: 'birdStand', color: '#8a5a3a', headColor: '#3a2a1a', legColor: '#4a8a5a', legLen: 24, neckLen: 12, accent: '#e8e4d4', bg1: '#e6dcc8', bg2: '#7a4a2a' } },
  { id: 'blacksmith-lapwing', name: 'Blacksmith Lapwing', sciName: 'Vanellus armatus', category: 'bird', rarity: 'common',
    habitat: 'Open ground near water',
    fact: 'Named for its metallic "tink-tink-tink" alarm call, which sounds just like a hammer striking an anvil.',
    icon: { shape: 'birdStand', color: '#1a1a1a', headColor: '#f0ece0', legColor: '#1a1a1a', legLen: 22, neckLen: 10, accent: '#1a1a1a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'temmincks-courser', name: "Temminck's Courser", sciName: 'Cursorius temminckii', category: 'bird', rarity: 'uncommon',
    habitat: 'Bare, recently burnt grassland',
    fact: 'It\'s drawn to freshly burnt plains, where the blackened ground makes the insects it hunts easy to spot.',
    icon: { shape: 'birdStand', color: '#c9a878', headColor: '#c9a878', legColor: '#e0c060', legLen: 20, neckLen: 8, accent: '#1a1a1a', bg1: '#eee3c8', bg2: '#b89868' } },
  { id: 'tawny-eagle', name: 'Tawny Eagle', sciName: 'Aquila rapax', category: 'bird', rarity: 'common',
    habitat: 'Perched on poles and dead trees across the plains',
    fact: 'An opportunist as much as a hunter, it will steal kills from smaller raptors and squabble with vultures over carcasses.',
    icon: { shape: 'birdPerch', color: '#a87f4a', headColor: '#a87f4a', hooked: true, accent: '#5a4a3a', bg1: '#e6d8bc', bg2: '#987040' } },
  { id: 'long-crested-eagle', name: 'Long-crested Eagle', sciName: 'Lophaetus occipitalis', category: 'bird', rarity: 'uncommon',
    habitat: 'Perched upright at forest edges, hunting rodents',
    fact: 'Its shaggy, floppy crest of feathers is unmistakable and often blows sideways in the wind while it perches.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', headColor: '#1a1a1a', hooked: true, crest: true, crestColor: '#1a1a1a', accent: '#e8b923', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'wahlbergs-eagle', name: "Wahlberg's Eagle", sciName: 'Hieraaetus wahlbergi', category: 'bird', rarity: 'common',
    habitat: 'Woodland edges, a common migrant visitor',
    fact: 'One of the most common migrant eagles in the Mara, arriving to breed each year and famously variable in colour from pale to almost black.',
    icon: { shape: 'birdPerch', color: '#6a5a48', headColor: '#6a5a48', hooked: true, accent: '#3a3a3a', bg1: '#dcd6c4', bg2: '#5a4a38' } },
  { id: 'augur-buzzard', name: 'Augur Buzzard', sciName: 'Buteo augur', category: 'bird', rarity: 'common',
    habitat: 'Perched on posts and rocky outcrops',
    fact: 'Pairs perform spectacular tumbling courtship flights high above their territory, calling loudly to each other as they dive.',
    icon: { shape: 'birdPerch', color: '#2a2a2a', headColor: '#2a2a2a', hooked: true, belly: '#f0ece0', accent: '#e0a83a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'african-harrier-hawk', name: 'African Harrier-Hawk', sciName: 'Polyboroides typus', category: 'bird', rarity: 'uncommon',
    habitat: 'Woodland and cliffs, raiding nests and palm fruit',
    fact: 'Its double-jointed legs bend backwards, letting it reach deep into tree holes and weaver nests to steal eggs and chicks.',
    icon: { shape: 'birdPerch', color: '#8a8a84', headColor: '#e8c090', hooked: true, accent: '#e8c090', bg1: '#dcdcd4', bg2: '#7a7a74' } },
  { id: 'black-shouldered-kite', name: 'Black-shouldered Kite', sciName: 'Elanus caeruleus', category: 'bird', rarity: 'common',
    habitat: 'Hovering over open grassland hunting rodents',
    fact: 'It hunts by hovering motionless in mid-air on rapidly beating wings, scanning the grass below for movement before dropping onto its prey.',
    icon: { shape: 'birdPerch', color: '#e6e2d4', headColor: '#e6e2d4', hooked: true, accent: '#c9302c', pattern: 'patches', bg1: '#eae6da', bg2: '#c9c4b4' } },
  { id: 'black-chested-snake-eagle', name: 'Black-chested Snake Eagle', sciName: 'Circaetus pectoralis', category: 'bird', rarity: 'uncommon',
    habitat: 'Soaring high over open plains hunting snakes',
    fact: 'It hunts snakes on the wing, dropping to snatch them and swallowing them whole, head first, even while still in flight.',
    icon: { shape: 'birdPerch', color: '#3a3a3a', headColor: '#3a3a3a', hooked: true, belly: '#f0ece0', accent: '#e8b923', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'dark-chanting-goshawk', name: 'Dark Chanting Goshawk', sciName: 'Melierax metabates', category: 'bird', rarity: 'common',
    habitat: 'Perched conspicuously in acacia trees',
    fact: 'Named for its melodic, whistling call, it will follow foraging mongooses and even people to snap up any insects flushed out.',
    icon: { shape: 'birdPerch', color: '#7a7a78', headColor: '#7a7a78', hooked: true, accent: '#e8b923', bg1: '#dedcd6', bg2: '#6a6a68' } },
  { id: 'gabar-goshawk', name: 'Gabar Goshawk', sciName: 'Micronisus gabar', category: 'bird', rarity: 'uncommon',
    habitat: 'Woodland, darting fast and low after small birds',
    fact: 'A dashing, agile hunter of small birds, it comes in both a grey form and a rarer, all-black melanistic form.',
    icon: { shape: 'birdPerch', color: '#5a5a5a', headColor: '#5a5a5a', hooked: true, accent: '#c9302c', bg1: '#dcdcdc', bg2: '#4a4a4a' } },
  { id: 'pygmy-falcon', name: 'Pygmy Falcon', sciName: 'Polihierax semitorquatus', category: 'bird', rarity: 'uncommon',
    habitat: 'Living inside old weaver nests in thorn trees',
    fact: 'Africa\'s smallest raptor, barely bigger than a sparrow, it nests almost exclusively inside the communal nests of white-headed buffalo weavers.',
    icon: { shape: 'birdPerch', color: '#e8e4d8', headColor: '#e8e4d8', hooked: true, accent: '#1a1a1a', bg1: '#eae6da', bg2: '#c9c4b4' } },
  { id: 'verreauxs-eagle-owl', name: "Verreaux's Eagle-Owl", sciName: 'Bubo lacteus', category: 'bird', rarity: 'rare',
    habitat: 'Roosting in large fig and sausage trees by day',
    fact: 'Africa\'s largest owl, it has striking bare pink eyelids and is powerful enough to prey on other raptors and small mammals like hares.',
    icon: { shape: 'birdPerch', color: '#a89880', headColor: '#a89880', hooked: true, pattern: 'patches', accent: '#e0708a', bg1: '#e6ddc8', bg2: '#988870' } },
  { id: 'spotted-eagle-owl', name: 'Spotted Eagle-Owl', sciName: 'Bubo africanus', category: 'bird', rarity: 'uncommon',
    habitat: 'Rocky outcrops and camp buildings at night',
    fact: 'Often heard rather than seen, its soft double hoot is one of the classic sounds of a Mara night around camp.',
    icon: { shape: 'birdPerch', color: '#7a7264', headColor: '#7a7264', hooked: true, pattern: 'patches', accent: '#e8b923', bg1: '#dcd8cc', bg2: '#6a6254' } },
  { id: 'pearl-spotted-owlet', name: 'Pearl-spotted Owlet', sciName: 'Glaucidium perlatum', category: 'bird', rarity: 'uncommon',
    habitat: 'Woodland, active by day as well as at night',
    fact: 'Small enough to fit in a hand, it has two false "eyes" on the back of its head to confuse would-be attackers from behind.',
    icon: { shape: 'birdPerch', color: '#8a6f4a', headColor: '#8a6f4a', hooked: true, pattern: 'patches', accent: '#e8b923', bg1: '#e2d6bc', bg2: '#7a6038' } },
  { id: 'black-bellied-bustard', name: 'Black-bellied Bustard', sciName: 'Lissotis melanogaster', category: 'bird', rarity: 'uncommon',
    habitat: 'Tall grassland, males calling with a distinctive pop',
    fact: 'The male\'s bizarre display call ends in a sound like a cork popping from a bottle, audible across open grassland.',
    icon: { shape: 'birdStand', color: '#c9b98e', headColor: '#e8e4d4', legColor: '#e8c060', legLen: 26, neckLen: 16, pattern: 'patches', accent: '#1a1a1a', bg1: '#eee6d0', bg2: '#b8a878' } },
  { id: 'double-banded-sandgrouse', name: 'Double-banded Sandgrouse', sciName: 'Pterocles bicinctus', category: 'bird', rarity: 'uncommon',
    habitat: 'Dry open ground, flying long distances to drink at dawn and dusk',
    fact: 'Males soak their belly feathers at waterholes at dawn and fly back to the nest so their chicks can drink from their soaked plumage.',
    icon: { shape: 'birdStand', color: '#a08d68', headColor: '#a08d68', legColor: '#8a7a58', legLen: 10, neckLen: 6, pattern: 'patches', accent: '#1a1a1a', bg1: '#e4dac0', bg2: '#907d58' } },
  { id: 'von-der-deckens-hornbill', name: "Von der Decken's Hornbill", sciName: 'Tockus deckeni', category: 'bird', rarity: 'common',
    habitat: 'Acacia woodland, hopping along branches',
    fact: 'Males have a bold red-and-ivory bill, while females have an all-black bill - one of the clearest male/female differences of any hornbill.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', headColor: '#1a1a1a', hooked: true, accent: '#c9302c', belly: '#f0ece0', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'african-grey-hornbill', name: 'African Grey Hornbill', sciName: 'Lophoceros nasutus', category: 'bird', rarity: 'common',
    habitat: 'Woodland and acacia scrub',
    fact: 'When nesting, the female seals herself into a tree hole with mud, leaving only a slit through which the male passes food for weeks.',
    icon: { shape: 'birdPerch', color: '#7a7264', headColor: '#7a7264', hooked: true, accent: '#3a3a3a', bg1: '#dcd8cc', bg2: '#6a6254' } },
  { id: 'red-billed-hornbill', name: 'Red-billed Hornbill', sciName: 'Tockus erythrorhynchus', category: 'bird', rarity: 'common',
    habitat: 'Dry woodland and camps, often quite tame',
    fact: 'It has a close mutualistic relationship with dwarf mongooses, calling out alarms in exchange for insects they flush up while foraging.',
    icon: { shape: 'birdPerch', color: '#3a3a3a', headColor: '#3a3a3a', hooked: true, pattern: 'patches', accent: '#c9302c', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'european-roller', name: 'European Roller', sciName: 'Coracias garrulus', category: 'bird', rarity: 'uncommon',
    habitat: 'Perched on wires and bushes, a migrant visitor',
    fact: 'This vivid blue migrant flies over 10,000km from Europe to spend the northern winter on the Mara\'s plains.',
    icon: { shape: 'birdPerch', color: '#3a7fc9', headColor: '#3a7fc9', accent: '#8a5a2a', belly: '#5a9fd9', bg1: '#d4e4f2', bg2: '#2a5f9c' } },
  { id: 'european-bee-eater', name: 'European Bee-eater', sciName: 'Merops apiaster', category: 'bird', rarity: 'uncommon',
    habitat: 'Perched in loose flocks on wires, a migrant visitor',
    fact: 'Huge flocks pass through the Mara on migration, filling the air with a constant liquid, rolling call.',
    icon: { shape: 'birdPerch', color: '#d9a52a', headColor: '#8a5a2a', accent: '#1a1a1a', belly: '#e8d060', bg1: '#f2e6c4', bg2: '#c98f1a' } },
  { id: 'white-fronted-bee-eater', name: 'White-fronted Bee-eater', sciName: 'Merops bullockoides', category: 'bird', rarity: 'common',
    habitat: 'Nesting colonially in riverbank burrows',
    fact: 'It nests in colonies of tunnels dug straight into sandy riverbanks, sometimes hundreds of burrows in a single cliff face.',
    icon: { shape: 'birdPerch', color: '#3a8a7a', headColor: '#1a1a1a', accent: '#c9302c', belly: '#e8e4d4', bg1: '#d4ece4', bg2: '#2a6a5a' } },
  { id: 'woodland-kingfisher', name: 'Woodland Kingfisher', sciName: 'Halcyon senegalensis', category: 'bird', rarity: 'common',
    habitat: 'Woodland, despite the name rarely seen near water',
    fact: 'Despite its name it rarely eats fish, instead hunting large insects, lizards, and even small birds from a high, exposed perch.',
    icon: { shape: 'birdPerch', color: '#1a5a9a', headColor: '#8a8a84', accent: '#c9302c', belly: '#8a8a84', bg1: '#d0e0ee', bg2: '#0a4a8a' } },
  { id: 'grey-headed-kingfisher', name: 'Grey-headed Kingfisher', sciName: 'Halcyon leucocephala', category: 'bird', rarity: 'uncommon',
    habitat: 'Woodland edges, a non-fishing kingfisher',
    fact: 'Another kingfisher that lives well away from water, it hunts grasshoppers and insects from low perches in dry bush.',
    icon: { shape: 'birdPerch', color: '#8a5a3a', headColor: '#8a8a84', accent: '#c9302c', belly: '#1a5a9a', bg1: '#e2d4c4', bg2: '#7a4a2a' } },
  { id: 'african-hoopoe', name: 'African Hoopoe', sciName: 'Upupa africana', category: 'bird', rarity: 'common',
    habitat: 'Lawns and open ground, probing for grubs',
    fact: 'Its crown of feathers fans open into a spectacular crest when it lands or is alarmed.',
    icon: { shape: 'birdPerch', color: '#c9823a', headColor: '#c9823a', crest: true, crestColor: '#c9302c', accent: '#1a1a1a', pattern: 'patches', bg1: '#eed8b8', bg2: '#b8722a' } },
  { id: 'green-wood-hoopoe', name: 'Green Wood-hoopoe', sciName: 'Phoeniculus purpureus', category: 'bird', rarity: 'common',
    habitat: 'Noisy family groups moving through woodland',
    fact: 'Highly social, family groups cackle loudly together in a raucous, rhythmic chorus that carries far through the trees.',
    icon: { shape: 'birdPerch', color: '#1a6a5a', headColor: '#1a6a5a', accent: '#c9302c', bg1: '#d0e6e0', bg2: '#0a5a4a' } },
  { id: 'silverbird', name: 'Silverbird', sciName: 'Empidornis semipartitus', category: 'bird', rarity: 'uncommon',
    habitat: 'Perched upright on low acacia branches',
    fact: 'A flycatcher found nowhere outside East Africa, named for the soft silvery-grey sheen across its back.',
    icon: { shape: 'birdPerch', color: '#b8b4a8', headColor: '#b8b4a8', accent: '#1a1a1a', belly: '#d9822a', bg1: '#e6e4dc', bg2: '#a8a498' } },
  { id: 'magpie-shrike', name: 'Magpie Shrike', sciName: 'Urolestes melanoleucus', category: 'bird', rarity: 'common',
    habitat: 'Perched in small groups atop bushes and termite mounds',
    fact: 'Also called the long-tailed fiscal, its tail can be almost as long as its whole body.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', headColor: '#1a1a1a', accent: '#1a1a1a', belly: '#f0ece0', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'northern-white-crowned-shrike', name: 'Northern White-crowned Shrike', sciName: 'Eurocephalus rueppelli', category: 'bird', rarity: 'common',
    habitat: 'Acacia woodland, in small chattering groups',
    fact: 'Unlike most shrikes it lives in cooperative family groups, with older offspring helping raise their younger siblings.',
    icon: { shape: 'birdPerch', color: '#c9c4b4', headColor: '#f0ece0', accent: '#1a1a1a', belly: '#f0ece0', bg1: '#e6e2d4', bg2: '#b8b4a4' } },
  { id: 'fork-tailed-drongo', name: 'Fork-tailed Drongo', sciName: 'Dicrurus adsimilis', category: 'bird', rarity: 'common',
    habitat: 'Perched conspicuously, chasing insects and mimicking alarm calls',
    fact: 'A notorious trickster, it mimics other species\' alarm calls to scare them off their food - then steals it.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', headColor: '#1a1a1a', accent: '#1a1a1a', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'pied-crow', name: 'Pied Crow', sciName: 'Corvus albus', category: 'bird', rarity: 'common',
    habitat: 'Widespread, often scavenging near camps and roads',
    fact: 'Highly intelligent and adaptable, it thrives alongside people and will problem-solve to reach hard-to-get food.',
    icon: { shape: 'birdPerch', color: '#1a1a1a', headColor: '#1a1a1a', accent: '#1a1a1a', belly: '#f0ece0', bg1: '#dcdcdc', bg2: '#2a2a2a' } },
  { id: 'speckled-mousebird', name: 'Speckled Mousebird', sciName: 'Colius striatus', category: 'bird', rarity: 'common',
    habitat: 'Thickets and gardens, scurrying through branches in small flocks',
    fact: 'It scampers along branches like a rodent using its feet and long tail for balance, giving the whole family its name.',
    icon: { shape: 'birdPerch', color: '#8a8268', crest: true, crestColor: '#8a8268', accent: '#1a1a1a', bg1: '#e2ddc8', bg2: '#7a7258' } },
  { id: 'white-browed-sparrow-weaver', name: 'White-browed Sparrow-Weaver', sciName: 'Plocepasser mahali', category: 'bird', rarity: 'common',
    habitat: 'Building scruffy straw nests in acacia trees',
    fact: 'Family groups build several messy, untidy nests per tree, using extra ones as decoys or emergency shelters.',
    icon: { shape: 'birdPerch', color: '#8a7a68', headColor: '#f0ece0', accent: '#8a5a2a', belly: '#f0ece0', bg1: '#e2dccb', bg2: '#7a6a58' } },
  { id: 'village-weaver', name: 'Village Weaver', sciName: 'Ploceus cucullatus', category: 'bird', rarity: 'common',
    habitat: 'Noisy colonies weaving nests over water',
    fact: 'Males weave intricate hanging nests and then hang upside down flapping their wings to advertise them to passing females, who inspect and often reject the workmanship.',
    icon: { shape: 'birdPerch', color: '#d9c92a', headColor: '#1a1a1a', accent: '#1a1a1a', belly: '#e8d94a', bg1: '#f2eec4', bg2: '#c9b91a' } },
  { id: 'red-billed-quelea', name: 'Red-billed Quelea', sciName: 'Quelea quelea', category: 'bird', rarity: 'common',
    habitat: 'Grassland, in flocks that can number in the millions',
    fact: 'Sometimes called Africa\'s "locust bird", it is the most abundant wild bird on Earth, with flocks so vast they can bend trees under their combined weight.',
    icon: { shape: 'birdPerch', color: '#c9a878', headColor: '#c9302c', accent: '#c9302c', bg1: '#eee3c8', bg2: '#b89868' } },
  { id: 'yellow-billed-oxpecker', name: 'Yellow-billed Oxpecker', sciName: 'Buphagus africanus', category: 'bird', rarity: 'uncommon',
    habitat: 'Riding on buffalo and hippo',
    fact: 'Distinguished from its red-billed cousin by its yellow-based bill and preference for riding on buffalo and hippo rather than giraffe.',
    icon: { shape: 'birdPerch', color: '#8a7a58', accent: '#e8c060', bg1: '#e2d8c0', bg2: '#7a6a48' } },
  { id: 'capped-wheatear', name: 'Capped Wheatear', sciName: 'Oenanthe pileata', category: 'bird', rarity: 'common',
    habitat: 'Short grassland, perching on low mounds and rocks',
    fact: 'It bobs and flicks its tail constantly while perched, flashing a bold black-and-white pattern each time it takes flight.',
    icon: { shape: 'birdPerch', color: '#c9b898', headColor: '#1a1a1a', accent: '#1a1a1a', belly: '#f0ece0', bg1: '#e8ddc4', bg2: '#b8a888' } },
  { id: 'rufous-naped-lark', name: 'Rufous-naped Lark', sciName: 'Mirafra africana', category: 'bird', rarity: 'common',
    habitat: 'Open grassland, singing from termite mounds',
    fact: 'Males sing from an exposed perch like a termite mound, then parachute back down to the ground in a fluttering display flight.',
    icon: { shape: 'birdPerch', color: '#a88a5a', crest: true, crestColor: '#8a5a2a', accent: '#1a1a1a', bg1: '#e6d8bc', bg2: '#987040' } },
];

if (typeof window !== 'undefined') window.SPECIES = SPECIES;
if (typeof module !== 'undefined') module.exports = { SPECIES };
